### PR TITLE
Add message reporting to uninstall

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Review by AlaaSarhan — COMMENTED** [review]
just noticed this now.. why did you choose to "inject" this through the method and not as a dependency through the constructor? I'd prefer constructor injection over a function argument here as it follows the common conventions out there

**Comment by JeroenDeDauw** [comment]
This MessageReporter is only used by install and uninstall. In most cases where DoctrineTermStore gets constructed you don't need this service at all. And in the one case where it is needed, you'd need to do extra parameter passing (or weirder stuff) to have the MessageReporter available when constructing the DoctrineTermStore.

**Comment by AlaaSarhan** [comment]
oh yeah right.. then I think install/uninstall functionality probably better to be extracted into their own class(es) .. that way it is also better for SRP and a logger/reporter becomes a good candidate for a dependency there

**Review by AlaaSarhan — APPROVED** [review]
extracting install/uninstall function into separate class(es) can be done in a separate PR

**Pull request merged**
